### ISSUE TITLE
Reproducing results on Tiny-Imagenet

### ISSUE THREAD

**Issue by yishayahu** [hanktseng131415go/UPANets#1]
I am trying to reproduce your results on Tiny-Imagenet.
I am running the command:
**python -m main --filters 64**
and getting the following error:
  File "/content/gdrive/My Drive/clustering_curriculum_v2/UPANets/models/upanets.py", line 194, in forward
    out0_spa = self.spa0(out0)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/gdrive/My Drive/clustering_curriculum_v2/UPANets/models/upanets.py", line 119, in forward
    x = self.sp_ffc(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 94, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)
**RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x1024 and 4096x1)**

**Comment by hanktseng131415go** [comment]
```
python -m main --filters 64
==> Preparing data..
Files already downloaded and verified
Files already downloaded and verified
==> Building model..

```
Hi @yishayahu , after reimplementing your cmd, the cmd can successfully build my model. Would you check why your output image size of block0 is 32x32 instead of 64x64? As this project is designed for classifying in Cifar and Tiny imagenet datasets, it is recommended that you manually change the input image size in this here https://github.com/hanktseng131415go/UPANets/blob/86d4a9c771a9dfe761d4107d20aecc1e909743fa/main.py#L123 

For example:
`net =  UPANets(args.filters, classes, args.blocks, 32)` for Cifar-10 of 32x32 images.

Please let me know that if you have any further question. Also, If there are enough demands for customizing input image size, we will update a more flexible version.

**Comment by hanktseng131415go** [comment]
Sorry I have not really answer your question.
I noticed you were trying to reimplement tiny imagenet result but the default datasets of args in the main.py is Cifar-10. You should change your cmd into:
`python -m main --datasets tiny_imgnet`

The main.py will automatcally change your image size to 64. The cause of your issue was because you inputed a default cifar-10 image size. However, your model was builded for input size in 64x64. 
Please be aware, the official image net is no longer supported for automatically download from Pytorch API. Therefore, you also should download the tiny imagenet dataset manually to the path `./data/tiny-imagenet-200/` or whenever you want to save. My method is send a request to the official [Imagenet](http://www.image-net.org/index) website. 

Besides, thank you for raising this issue so we found another error when counting model params in summary. Please pull the latest version of this project to make it work properly. And I have checked that the cmd:
```
python -m main --datasets tiny_imgnet
==> Preparing data..
==> Building model..
```
can work.

**Comment by yishayahu** [comment]
I actually changed the default parameters inside the code of main. so it was running on Tiny-Imagenet and did not work.
now it is working, the problem really was this line:
summary(net, (3, 32, 32))
thanks a lot for your help:)
